# voice_assistant/config.py

import os
from dotenv import load_dotenv

# Load environment variables from the .env file
load_dotenv()

class Config:
    """
    Configuration class to hold the model selection and API keys for Deepgram and Groq.
    
    Attributes:
        TRANSCRIPTION_MODEL (str): The model to use for transcription ('deepgram').
        RESPONSE_MODEL (str): The model to use for response generation ('groq').
        TTS_MODEL (str): The model to use for text-to-speech ('deepgram').
        GROQ_API_KEY (str): API key for Groq services.
        DEEPGRAM_API_KEY (str): API key for Deepgram services.
    """
    # Model selection
    TRANSCRIPTION_MODEL = 'deepgram'  # Only deepgram supported
    RESPONSE_MODEL = 'groq'  # Only groq supported
    TTS_MODEL = 'deepgram'  # Only deepgram supported

    # LLM Selection
    GROQ_LLM = "llama3-8b-8192"

    # API keys
    GROQ_API_KEY = os.getenv("GROQ_API_KEY")
    DEEPGRAM_API_KEY = os.getenv("DEEPGRAM_API_KEY")

    # Temp file generated by the STT model
    INPUT_AUDIO = "test.mp3"

    @staticmethod
    def validate_config():
        """
        Validate the configuration to ensure all necessary environment variables are set.
        
        Raises:
            ValueError: If a required environment variable is not set or invalid.
        """
        # Ensure that the transcription, TTS, and response models are valid
        Config._validate_model('TRANSCRIPTION_MODEL', ['deepgram'])
        Config._validate_model('TTS_MODEL', ['deepgram'])
        Config._validate_model('RESPONSE_MODEL', ['groq'])

        # Validate API keys for the selected models
        Config._validate_api_key('TRANSCRIPTION_MODEL', 'deepgram', 'DEEPGRAM_API_KEY')
        Config._validate_api_key('TTS_MODEL', 'deepgram', 'DEEPGRAM_API_KEY')
        Config._validate_api_key('RESPONSE_MODEL', 'groq', 'GROQ_API_KEY')

    @staticmethod
    def _validate_model(attribute, valid_options):
        """
        Validate that the model selection is within the allowed options.
        """
        model = getattr(Config, attribute)
        if model not in valid_options:
            raise ValueError(
                f"Invalid {attribute}. Must be one of {valid_options}"
            )

    @staticmethod
    def _validate_api_key(model_attr, model_value, api_key_attr):
        """
        Validate that the necessary API key for a model is set.
        """
        if getattr(Config, model_attr) == model_value and not getattr(Config, api_key_attr):
            raise ValueError(f"{api_key_attr} is required for {model_value} models")
